export const REGISTER_USER = 'REGISTER_USER';

export const UPDATE_GEOLOCATION = 'UPDATE_GEOLOCATION';

export const UPDATE_STATUS = 'UPDATE_STATUS';

export const UPDATE_WAITING_STATUS = 'UPDATE_WAITING_STATUS';

export const UPDATE_LAST_UPLOAD_TIME = 'UPDATE_LAST_UPLOAD_TIME';
